<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Framework\ModularMonolith.Framework.DataAccess\ModularMonolith.Framework.DataAccess.csproj" />
      <ProjectReference Include="..\ModularMonolith.Module.Builder.Domain\ModularMonolith.Module.Builder.Domain.csproj" />
    </ItemGroup>

</Project>

