<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ModularMonolith.Framework.UseCases.Implementation\ModularMonolith.Framework.UseCases.Implementation.csproj" />
      <ProjectReference Include="..\ModularMonolith.Framework.Utils\ModularMonolith.Framework.Utils.csproj" />
      <ProjectReference Include="..\ModularMonolith.Module.Template.Contract.Implementation\ModularMonolith.Module.Template.Contract.Implementation.csproj" />
      <ProjectReference Include="..\ModularMonolith.Module.Builder.Contracts.Implementation\ModularMonolith.Module.Builder.Contracts.Implementation.csproj" />
    </ItemGroup>

</Project>
