<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Quartz" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ModularMonolith.Module.Template.DataAccess.Interface\ModularMonolith.Module.Template.DataAccess.Interface.csproj" />
    </ItemGroup>

</Project>
