<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ModularMonolith.Module.Builder.Contracts\ModularMonolith.Module.Builder.Contracts.csproj" />
    </ItemGroup>

</Project>

