// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModularMonolith.Module.Builder.DataAccess.Sqlite;

#nullable disable

namespace ModularMonolith.Module.Builder.DataAccess.Sqlite.Migrations
{
    [DbContext(typeof(BuilderDbContext))]
    [Migration("20260823121950_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Builder")
                .HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ModularMonolith.Module.Builder.Domain.Agreggates.Builder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Builders", "Builder");
                });
#pragma warning restore 612, 618
        }
    }
}
