<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Template\Commands\" />
      <Folder Include="Template\Dto\" />
      <Folder Include="Template\Mappings\" />
      <Folder Include="Template\Queries\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Mapster" />
      <PackageReference Include="MediatR" />
    </ItemGroup>
    

    <ItemGroup>
      <ProjectReference Include="..\ModularMonolith.Module.Template.Contract\ModularMonolith.Module.Template.Contract.csproj" />
    </ItemGroup>

</Project>
