<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" />
      <PackageReference Include="Quartz.Extensions.DependencyInjection" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Framework\ModularMonolith.Framework.DataAccess\ModularMonolith.Framework.DataAccess.csproj" />
      <ProjectReference Include="..\..\..\Framework\ModularMonolith.Framework.Utils\ModularMonolith.Framework.Utils.csproj" />
      <ProjectReference Include="..\..\Template\ModularMonolith.Module.Template.Contract\ModularMonolith.Module.Template.Contract.csproj" />
    </ItemGroup>

</Project>

